import pygame

# Important.
FPS = 75

# Dimensions.
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 800

# Misc.
WINDOW_CAPTION = "Spaceships Remaster"
ANIMATION_SPEED = 0.1

# Gameplay.
PLAYER_VEL = 4
PLAYER_BULLET_VEL = 5
PLAYER_MAX_BULLET = 4
PLAYER_HEALTH = 3
PLAYER_SHIELD = 5
PLAYER_BULLET_COOLDOWN = 500
ENEMY_VEL = 1
ENEMY_BULLET_VEL = 2
ENEMY_HEALTH = 2
ENEMY_BULLET_COOLDOWN = 4000
ENEMY_COOLDOWN = 2000
ENEMY_PASSING_EVENT = pygame.USEREVENT + 1
