import pygame

# Important.
FPS = 75

# Dimensions.
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 800

# Misc.
WINDOW_CAPTION = "Spaceships Remaster"
ANIMATION_SPEED = 0.15

# Gameplay.
PLAYER_SIZE = (64, 64)
PLAYER_VEL = 4
PLAYER_BULLET_VEL = 5
PLAYER_BULLET_DAMAGE = 1
PLAYER_MAX_HEALTH = 10
PLAYER_SHIELD = 5
ENEMY_SIZE = (64, 64)
ENEMY_VEL = 1
ENEMY_BULLET_VEL = 2
ENEMY_BULLET_DAMAGE = 1
ENEMY_COLLISION_DAMAGE = 2
ENEMY_MAX_HEALTH = 3
ENEMY_BULLET_COOLDOWN = 4000
ENEMY_SPAWN_COOLDOWN = 2000
ENEMY_SPAWN_EVENT = pygame.USEREVENT + 1
ENEMY_PASSING_EVENT = pygame.USEREVENT + 2
ENEMY_TYPES = ["black", "blue", "green", "red", "red_longwing"]
